<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7hjcwBG' shared service.

return $this->privates['.service_locator.7hjcwBG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'paramFetcher' => ['privates', '.errored..service_locator.7hjcwBG.FOS\\RestBundle\\Request\\ParamFetcher', NULL, 'Cannot autowire service ".service_locator.7hjcwBG": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.'],
], [
    'paramFetcher' => 'FOS\\RestBundle\\Request\\ParamFetcher',
]);
