<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAe7ZCH3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAe7ZCH3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAe7ZCH3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAe7ZCH3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAe7ZCH3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ae7ZCH3',
    'container.build_id' => '03eee5cc',
    'container.build_time' => 1568122628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAe7ZCH3');
