<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_article_getarticle' => [[], ['_controller' => 'App\\Controller\\ArticleController::getArticleAction'], [], [['text', '/api/articles']], [], []],
    'app_article_postarticle' => [[], ['_controller' => 'App\\Controller\\ArticleController::postArticleAction'], [], [['text', '/api/article']], [], []],
    'db' => [[], ['_controller' => 'App\\Controller\\DbController::index'], [], [['text', '/db']], [], []],
    'post' => [[], ['_controller' => 'App\\Controller\\DbController::Lists'], [], [['text', '/postttt']], [], []],
    'count' => [[], ['_controller' => 'App\\Controller\\DbController::Home'], [], [['text', '/count']], [], []],
    'curl' => [['title'], ['_controller' => 'App\\Controller\\DbController::curlPost'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/curl']], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\DbController::test'], [], [['text', '/test']], [], []],
    'background_list' => [['id'], ['_controller' => 'App\\Controller\\TestController::backgroundListAction', '_format' => 'json'], [], [['text', '/background'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
    'get_lists' => [[], ['_controller' => 'App\\Controller\\TestController::getListsAction', '_format' => 'json'], [], [['text', '/api/lists']], [], []],
    'get_list' => [['id'], ['_controller' => 'App\\Controller\\TestController::getListAction', '_format' => 'json'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
    'post_lists' => [[], ['_controller' => 'App\\Controller\\TestController::postListsAction', '_format' => 'json'], [], [['text', '/api/lists']], [], []],
    'get_lists_task' => [['id'], ['_controller' => 'App\\Controller\\TestController::getListsTaskAction', '_format' => 'json'], [], [['text', '/task'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
    'put_lists' => [[], ['_controller' => 'App\\Controller\\TestController::putListsAction', '_format' => 'json'], [], [['text', '/api/lists']], [], []],
    'patch_lists' => [['id'], ['_controller' => 'App\\Controller\\TestController::patchListsAction', '_format' => 'json'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/lists']], [], []],
];
