#index:
#    path: /
#    controller: App\Controller\DefaultController::index

listes:
    type      : rest
    resource  : App\Controller\TestController
    prefix    : api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"    