<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.An7q4KS' shared service.

return $this->privates['.service_locator.An7q4KS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DbController::test' => ['privates', '.service_locator.7hjcwBG', 'get_ServiceLocator_7hjcwBGService.php', true],
    'App\\Controller\\TestController::__contruct' => ['privates', '.service_locator.Lbx1wL6', 'get_ServiceLocator_Lbx1wL6Service.php', true],
    'App\\Controller\\TestController::backgroundListAction' => ['privates', '.service_locator.7hjcwBG', 'get_ServiceLocator_7hjcwBGService.php', true],
    'App\\Controller\\TestController::postListsAction' => ['privates', '.service_locator.7hjcwBG', 'get_ServiceLocator_7hjcwBGService.php', true],
    'App\\Controller\\TestController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ArticleController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DbController:test' => ['privates', '.service_locator.7hjcwBG', 'get_ServiceLocator_7hjcwBGService.php', true],
    'App\\Controller\\TestController:__contruct' => ['privates', '.service_locator.Lbx1wL6', 'get_ServiceLocator_Lbx1wL6Service.php', true],
    'App\\Controller\\TestController:backgroundListAction' => ['privates', '.service_locator.7hjcwBG', 'get_ServiceLocator_7hjcwBGService.php', true],
    'App\\Controller\\TestController:postListsAction' => ['privates', '.service_locator.7hjcwBG', 'get_ServiceLocator_7hjcwBGService.php', true],
    'App\\Controller\\TestController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\ArticleController::setViewHandler' => '?',
    'App\\Controller\\DbController::test' => '?',
    'App\\Controller\\TestController::__contruct' => '?',
    'App\\Controller\\TestController::backgroundListAction' => '?',
    'App\\Controller\\TestController::postListsAction' => '?',
    'App\\Controller\\TestController::setViewHandler' => '?',
    'App\\Controller\\ArticleController:setViewHandler' => '?',
    'App\\Controller\\DbController:test' => '?',
    'App\\Controller\\TestController:__contruct' => '?',
    'App\\Controller\\TestController:backgroundListAction' => '?',
    'App\\Controller\\TestController:postListsAction' => '?',
    'App\\Controller\\TestController:setViewHandler' => '?',
]);
